# Generated by Django 4.2.6 on 2024-04-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_image_disliked_by_image_liked_by_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagereaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imagereaction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagereaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageReaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
